---
- name: "create VLANs"
  cisco.ios.ios_config:
    lines: 
      - name {{item.name}}
    parents: vlan {{item.id}}
  loop: "{{vlan_config}}"
  notify: save_running_config

- name: configure SVIs 
  cisco.ios.ios_config:
    lines:
      - ip address {{item.ip}} 255.255.255.0
      - ipv6 enable
      - ospfv3 1 ipv4 area 0
      - no shutdown
    parents: interface vlan {{item.id}}
  loop: "{{vlan_config}}"
  notify: save_running_config
